mysite/common/urls.py
import imp
from re import template
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import base_views

#url 매핑 시 항상 마지막에 '/' 붙여줄 것
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),    #'/'에 해당되는 path
]

mysite/myapp/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'myapp'

urlpatterns = [
    #base_views
    path('', base_views.index, name = 'index'),
    path('<int:question_id>/', base_views.detail, name = 'detail'),
    
    #question_views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    
    #answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
]

mysite/myapp/views/base_views.py
#가상환경 접속 : E:\backend\django\mysite>mysite.cmd
#가상환경 종료 : deactivate
#주석 단축키 : ctrl + /
#admin / 1111
#user2 / passworduser2!
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Question

#질문 목록 화면
def index(request):
    page = request.GET.get('page', '1')     #디폴트 페이지 : 1
    kw = request.GET.get('kw', '')      #검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |      #제목
            Q(content__icontains=kw) |      #내용
            Q(answer__content__icontains=kw) |      #답변 내용
            Q(author__username__icontains=kw) |     #질문 글쓴이
            Q(answer__author__username__icontains=kw)       #답변 글쓴이
        ).distinct()
    paginator = Paginator(question_list, 10)    #10항목씩 출력
    page_obj = paginator.get_page(page)
    context = {"question_list" : page_obj}
    return render(request, "myapp/question_list.html", context)

#질문 상세 내용 화면
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "myapp/question_detail.html", context)

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!--필요한 메타 태그-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--부트스트랩 CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!--마이앱 CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, myapp!</title>
</head>
<body>
    <!--네비게이션 바-->
    {% include "navbar.html" %}
    <!--기본 탬플릿 안에 삽입될 내용 시작-->
    {% block content %}
    {% endblock %}
    <!--기본 탬플릿 안에 삽입될 내용 끝-->
    <!--부트스트랩 JS-->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!--자바스크립트 시작-->
    {% block script %}
    {% endblock %}
    <!--자바스크립트 종료-->
</body>
</html>

mysite/templates/form_errors.html
<!--에러 출력-->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}

    <!--필드 오류-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

    <!--넌필드 오류-->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

mysite/templates/navbar.html
<!--네비게이션 바--> 
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'myapp:index' %}">myapp</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                area-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}      <!--로그인 되었는지 검사-->
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>